name: birthday_app
description: Offline-first People and Events reminder app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.3.6
  go_router: ^13.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.0.15
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  workmanager: ^0.5.1
  android_alarm_manager_plus: ^2.1.0
  file_picker: ^8.0.0
  csv: ^6.0.0
  excel: ^4.0.2
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  golden_toolkit: ^0.15.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  drift_dev: ^2.13.0
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  generate: true
